=begin
Book Sharing API

This is a backend for distributed library application

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class BookState
    attr_accessor :book

    attr_accessor :current_status

    attr_accessor :uploaded_by

    attr_accessor :lent_by

    attr_accessor :lost_by

    attr_accessor :returned_by

    attr_accessor :requested_by

    attr_accessor :created_at

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'book' => :'book',
        
        :'current_status' => :'currentStatus',
        
        :'uploaded_by' => :'uploadedBy',
        
        :'lent_by' => :'lentBy',
        
        :'lost_by' => :'lostBy',
        
        :'returned_by' => :'returnedBy',
        
        :'requested_by' => :'requestedBy',
        
        :'created_at' => :'createdAt',
        
        :'updated_at' => :'updatedAt'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'book' => :'Book',
        :'current_status' => :'String',
        :'uploaded_by' => :'ResponseUser',
        :'lent_by' => :'ResponseUser',
        :'lost_by' => :'ResponseUser',
        :'returned_by' => :'ResponseUser',
        :'requested_by' => :'Array<ResponseUser>',
        :'created_at' => :'DateTime',
        :'updated_at' => :'DateTime'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'book']
        self.book = attributes[:'book']
      end
      
      if attributes[:'currentStatus']
        self.current_status = attributes[:'currentStatus']
      end
      
      if attributes[:'uploadedBy']
        self.uploaded_by = attributes[:'uploadedBy']
      end
      
      if attributes[:'lentBy']
        self.lent_by = attributes[:'lentBy']
      end
      
      if attributes[:'lostBy']
        self.lost_by = attributes[:'lostBy']
      end
      
      if attributes[:'returnedBy']
        self.returned_by = attributes[:'returnedBy']
      end
      
      if attributes[:'requestedBy']
        if (value = attributes[:'requestedBy']).is_a?(Array)
          self.requested_by = value
        end
      end
      
      if attributes[:'createdAt']
        self.created_at = attributes[:'createdAt']
      end
      
      if attributes[:'updatedAt']
        self.updated_at = attributes[:'updatedAt']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          book == o.book &&
          current_status == o.current_status &&
          uploaded_by == o.uploaded_by &&
          lent_by == o.lent_by &&
          lost_by == o.lost_by &&
          returned_by == o.returned_by &&
          requested_by == o.requested_by &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [book, current_status, uploaded_by, lent_by, lost_by, returned_by, requested_by, created_at, updated_at].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
