<?php
/**
 * UserReportsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserReportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserReportsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for getBorrowedBooksByUser
     *
     * Returns list of books borrowed by the current logged-in user or list of books user is currently reading
     *
     */
    public function test_getBorrowedBooksByUser() {

    }
    
    /**
     * Test case for getLentBooksByUser
     *
     * Returns list of books lent by the current logged-in user.
     *
     */
    public function test_getLentBooksByUser() {

    }
    
    /**
     * Test case for getLostBooksByUser
     *
     * Returns list of books lost by the current logged-in user
     *
     */
    public function test_getLostBooksByUser() {

    }
    
    /**
     * Test case for getRequestedBooksByUser
     *
     * Returns list of books requested by the current logged-in user
     *
     */
    public function test_getRequestedBooksByUser() {

    }
    
    /**
     * Test case for getReturnedBooksByUser
     *
     * Returns list of books read by the current logged-in user
     *
     */
    public function test_getReturnedBooksByUser() {

    }
    
}
