=begin
Book Sharing API

This is a backend for distributed library application

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require "uri"

module SwaggerClient
  class BookSearchApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Returns list of books written by the requested author{s}
    # Returns list of books written by the requested author{s}
    # @param author Name of the author by which books can be searched
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Number of books to be retrieved
    # @option opts [Integer] :page Page number from where we want to start fetching books
    # @return [nil]
    def search_by_author(author, opts = {})
      search_by_author_with_http_info(author, opts)
      return nil
    end

    # Returns list of books written by the requested author{s}
    # Returns list of books written by the requested author{s}
    # @param author Name of the author by which books can be searched
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Number of books to be retrieved
    # @option opts [Integer] :page Page number from where we want to start fetching books
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def search_by_author_with_http_info(author, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: BookSearchApi#search_by_author ..."
      end
      
      # verify the required parameter 'author' is set
      fail "Missing the required parameter 'author' when calling search_by_author" if author.nil?
      
      # resource path
      local_var_path = "/book/search/by-author".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'author'] = @api_client.build_collection_param(author, :csv)
      query_params[:'limit'] = opts[:'limit'] if opts[:'limit']
      query_params[:'page'] = opts[:'page'] if opts[:'page']

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      _header_accept = []
      _header_accept_result = @api_client.select_header_accept(_header_accept) and header_params['Accept'] = _header_accept_result

      # HTTP header 'Content-Type'
      _header_content_type = []
      header_params['Content-Type'] = @api_client.select_header_content_type(_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BookSearchApi#search_by_author\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Returns list of books having the requested tag{s}
    # Returns list of books having the requested tag{s}
    # @param tags List of tags by which books can be searched
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Number of books to be retrieved
    # @option opts [Integer] :page Page number from where we want to start fetching books
    # @return [nil]
    def search_by_tags(tags, opts = {})
      search_by_tags_with_http_info(tags, opts)
      return nil
    end

    # Returns list of books having the requested tag{s}
    # Returns list of books having the requested tag{s}
    # @param tags List of tags by which books can be searched
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Number of books to be retrieved
    # @option opts [Integer] :page Page number from where we want to start fetching books
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def search_by_tags_with_http_info(tags, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: BookSearchApi#search_by_tags ..."
      end
      
      # verify the required parameter 'tags' is set
      fail "Missing the required parameter 'tags' when calling search_by_tags" if tags.nil?
      
      # resource path
      local_var_path = "/book/search/by-tags".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'tags'] = @api_client.build_collection_param(tags, :csv)
      query_params[:'limit'] = opts[:'limit'] if opts[:'limit']
      query_params[:'page'] = opts[:'page'] if opts[:'page']

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      _header_accept = []
      _header_accept_result = @api_client.select_header_accept(_header_accept) and header_params['Accept'] = _header_accept_result

      # HTTP header 'Content-Type'
      _header_content_type = []
      header_params['Content-Type'] = @api_client.select_header_content_type(_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BookSearchApi#search_by_tags\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Returns list of books which have similar requested name
    # Returns list of books which have similar requested name
    # @param name Name of the book by which books can be searched
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Number of books to be retrieved
    # @option opts [Integer] :page Page number from where we want to start fetching books
    # @return [nil]
    def search_like_name(name, opts = {})
      search_like_name_with_http_info(name, opts)
      return nil
    end

    # Returns list of books which have similar requested name
    # Returns list of books which have similar requested name
    # @param name Name of the book by which books can be searched
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :limit Number of books to be retrieved
    # @option opts [Integer] :page Page number from where we want to start fetching books
    # @return [Array<(nil, Fixnum, Hash)>] nil, response status code and response headers
    def search_like_name_with_http_info(name, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: BookSearchApi#search_like_name ..."
      end
      
      # verify the required parameter 'name' is set
      fail "Missing the required parameter 'name' when calling search_like_name" if name.nil?
      
      # resource path
      local_var_path = "/book/search/like-name/{name}".sub('{format}','json').sub('{' + 'name' + '}', name.to_s)

      # query parameters
      query_params = {}
      query_params[:'limit'] = opts[:'limit'] if opts[:'limit']
      query_params[:'page'] = opts[:'page'] if opts[:'page']

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      _header_accept = []
      _header_accept_result = @api_client.select_header_accept(_header_accept) and header_params['Accept'] = _header_accept_result

      # HTTP header 'Content-Type'
      _header_content_type = []
      header_params['Content-Type'] = @api_client.select_header_content_type(_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BookSearchApi#search_like_name\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
