<?php
/**
 * BookApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BookApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BookApi
{

    /**
     * API Client
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://localhost/api');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     * @return BookApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * addBook
     *
     * Creates a book
     *
     * @param \Swagger\Client\Model\NewBook $body Book object which needs to be added to the library (required)
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function addBook($body, $authorization)
    {
        list($response, $statusCode, $httpHeader) = $this->addBookWithHttpInfo ($body, $authorization);
        return $response; 
    }


    /**
     * addBookWithHttpInfo
     *
     * Creates a book
     *
     * @param \Swagger\Client\Model\NewBook $body Book object which needs to be added to the library (required)
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function addBookWithHttpInfo($body, $authorization)
    {
        
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addBook');
        }
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException('Missing the required parameter $authorization when calling addBook');
        }
  
        // parse inputs
        $resourcePath = "/book";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        // header params
        
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * delete
     *
     * Deletes book details
     *
     * @param string $book_id Id of the book to be modified (required)
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function delete($book_id, $authorization)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteWithHttpInfo ($book_id, $authorization);
        return $response; 
    }


    /**
     * deleteWithHttpInfo
     *
     * Deletes book details
     *
     * @param string $book_id Id of the book to be modified (required)
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteWithHttpInfo($book_id, $authorization)
    {
        
        // verify the required parameter 'book_id' is set
        if ($book_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $book_id when calling delete');
        }
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException('Missing the required parameter $authorization when calling delete');
        }
  
        // parse inputs
        $resourcePath = "/book/{bookId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        // header params
        
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        
        if ($book_id !== null) {
            $resourcePath = str_replace(
                "{" . "bookId" . "}",
                $this->apiClient->getSerializer()->toPathValue($book_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * getBookById
     *
     * Retrieves a book
     *
     * @param string $book_id The id of book to be retrieved (required)
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getBookById($book_id, $authorization)
    {
        list($response, $statusCode, $httpHeader) = $this->getBookByIdWithHttpInfo ($book_id, $authorization);
        return $response; 
    }


    /**
     * getBookByIdWithHttpInfo
     *
     * Retrieves a book
     *
     * @param string $book_id The id of book to be retrieved (required)
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getBookByIdWithHttpInfo($book_id, $authorization)
    {
        
        // verify the required parameter 'book_id' is set
        if ($book_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $book_id when calling getBookById');
        }
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException('Missing the required parameter $authorization when calling getBookById');
        }
  
        // parse inputs
        $resourcePath = "/book/{bookId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        // header params
        
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        
        if ($book_id !== null) {
            $resourcePath = str_replace(
                "{" . "bookId" . "}",
                $this->apiClient->getSerializer()->toPathValue($book_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * getBooks
     *
     * Retrieves list of books
     *
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getBooks($authorization, $limit = null, $page = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getBooksWithHttpInfo ($authorization, $limit, $page);
        return $response; 
    }


    /**
     * getBooksWithHttpInfo
     *
     * Retrieves list of books
     *
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getBooksWithHttpInfo($authorization, $limit = null, $page = null)
    {
        
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException('Missing the required parameter $authorization when calling getBooks');
        }
  
        // parse inputs
        $resourcePath = "/books";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }
        // header params
        
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * put
     *
     * Updates book details
     *
     * @param string $book_id Id of the book to be modified (required)
     * @param \Swagger\Client\Model\NewBook $body Book object details which needs to be updated (required)
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function put($book_id, $body, $authorization)
    {
        list($response, $statusCode, $httpHeader) = $this->putWithHttpInfo ($book_id, $body, $authorization);
        return $response; 
    }


    /**
     * putWithHttpInfo
     *
     * Updates book details
     *
     * @param string $book_id Id of the book to be modified (required)
     * @param \Swagger\Client\Model\NewBook $body Book object details which needs to be updated (required)
     * @param string $authorization Token which needs to be sent as \&quot;Authorization: Bearer XXXXXX\&quot;  (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function putWithHttpInfo($book_id, $body, $authorization)
    {
        
        // verify the required parameter 'book_id' is set
        if ($book_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $book_id when calling put');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling put');
        }
        // verify the required parameter 'authorization' is set
        if ($authorization === null) {
            throw new \InvalidArgumentException('Missing the required parameter $authorization when calling put');
        }
  
        // parse inputs
        $resourcePath = "/book/{bookId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        // header params
        
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        
        if ($book_id !== null) {
            $resourcePath = str_replace(
                "{" . "bookId" . "}",
                $this->apiClient->getSerializer()->toPathValue($book_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
}
