<?php
/**
 * UserReportsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserReportsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserReportsApi
{

    /**
     * API Client
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://localhost/api');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     * @return UserReportsApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * getBorrowedBooksByUser
     *
     * Returns list of books borrowed by the current logged-in user or list of books user is currently reading
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books (optional)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getBorrowedBooksByUser($limit = null, $page = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getBorrowedBooksByUserWithHttpInfo ($limit, $page);
        return $response; 
    }


    /**
     * getBorrowedBooksByUserWithHttpInfo
     *
     * Returns list of books borrowed by the current logged-in user or list of books user is currently reading
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books (optional)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getBorrowedBooksByUserWithHttpInfo($limit = null, $page = null)
    {
        
  
        // parse inputs
        $resourcePath = "/user/reports/borrowed-books";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * getLentBooksByUser
     *
     * Returns list of books lent by the current logged-in user.
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getLentBooksByUser($limit = null, $page = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getLentBooksByUserWithHttpInfo ($limit, $page);
        return $response; 
    }


    /**
     * getLentBooksByUserWithHttpInfo
     *
     * Returns list of books lent by the current logged-in user.
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getLentBooksByUserWithHttpInfo($limit = null, $page = null)
    {
        
  
        // parse inputs
        $resourcePath = "/user/reports/lent-books";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * getLostBooksByUser
     *
     * Returns list of books lost by the current logged-in user
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getLostBooksByUser($limit = null, $page = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getLostBooksByUserWithHttpInfo ($limit, $page);
        return $response; 
    }


    /**
     * getLostBooksByUserWithHttpInfo
     *
     * Returns list of books lost by the current logged-in user
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getLostBooksByUserWithHttpInfo($limit = null, $page = null)
    {
        
  
        // parse inputs
        $resourcePath = "/user/reports/lost-books";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * getRequestedBooksByUser
     *
     * Returns list of books requested by the current logged-in user
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getRequestedBooksByUser($limit = null, $page = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getRequestedBooksByUserWithHttpInfo ($limit, $page);
        return $response; 
    }


    /**
     * getRequestedBooksByUserWithHttpInfo
     *
     * Returns list of books requested by the current logged-in user
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getRequestedBooksByUserWithHttpInfo($limit = null, $page = null)
    {
        
  
        // parse inputs
        $resourcePath = "/user/reports/requested-books";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
    /**
     * getReturnedBooksByUser
     *
     * Returns list of books read by the current logged-in user
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getReturnedBooksByUser($limit = null, $page = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getReturnedBooksByUserWithHttpInfo ($limit, $page);
        return $response; 
    }


    /**
     * getReturnedBooksByUserWithHttpInfo
     *
     * Returns list of books read by the current logged-in user
     *
     * @param int $limit Number of books to be retrieved (optional)
     * @param int $page Page number from where we want to start fetching books. (optional)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getReturnedBooksByUserWithHttpInfo($limit = null, $page = null)
    {
        
  
        // parse inputs
        $resourcePath = "/user/reports/returned-books";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );
            
            return array(null, $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
  
            throw $e;
        }
    }
    
}
