=begin
Book Sharing API

This is a backend for distributed library application

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::NewAuthor
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NewAuthor' do
  before do
    # run before each test
    @instance = SwaggerClient::NewAuthor.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NewAuthor' do
    it 'should create an instact of NewAuthor' do
      @instance.should be_a(SwaggerClient::NewAuthor) 
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

