=begin
Book Sharing API

This is a backend for distributed library application

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::UserReportsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserReportsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::UserReportsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserReportsApi' do
    it 'should create an instact of UserReportsApi' do
      @instance.should be_a(SwaggerClient::UserReportsApi)
    end
  end

  # unit tests for get_borrowed_books_by_user
  # Returns list of books borrowed by the current logged-in user or list of books user is currently reading
  # Returns list of books borrowed by the user
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of books to be retrieved
  # @option opts [Integer] :page Page number from where we want to start fetching books
  # @return [nil]
  describe 'get_borrowed_books_by_user test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for get_lent_books_by_user
  # Returns list of books lent by the current logged-in user.
  # Returns list of books lent by the user
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of books to be retrieved
  # @option opts [Integer] :page Page number from where we want to start fetching books.
  # @return [nil]
  describe 'get_lent_books_by_user test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for get_lost_books_by_user
  # Returns list of books lost by the current logged-in user
  # Returns list of books lost by the user
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of books to be retrieved
  # @option opts [Integer] :page Page number from where we want to start fetching books.
  # @return [nil]
  describe 'get_lost_books_by_user test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for get_requested_books_by_user
  # Returns list of books requested by the current logged-in user
  # Returns list of books requested by the user
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of books to be retrieved
  # @option opts [Integer] :page Page number from where we want to start fetching books.
  # @return [nil]
  describe 'get_requested_books_by_user test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for get_returned_books_by_user
  # Returns list of books read by the current logged-in user
  # Returns list of books read by the user
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of books to be retrieved
  # @option opts [Integer] :page Page number from where we want to start fetching books.
  # @return [nil]
  describe 'get_returned_books_by_user test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
